### ISSUE TITLE
DC/OS application group support

### ISSUE THREAD

**Issue by siggy** [BuoyantIO/linkerd-viz#6]
linkerd-viz does not properly aggregate metrics from DC/OS applications deployed as part of groups.

For example, an app named `my-group/webapp` yields metrics like this:

```
rt:outgoing:dst:id:_:io_l5d_marathon:my_group:webapp:requests 11
```

the last two `metrics_relabel` steps defined at:
https://github.com/BuoyantIO/linkerd-viz/blob/master/dcos/prometheus-dcos.yml#L32

.... cause the metric to be rewritten as:

```
linkerd:incoming:webapp:requests{instance="10.0.2.164",job="linkerd",service="my_group"}
```

...when the expected metric should be:

```
linkerd:incoming:requests{instance="10.0.2.164",job="linkerd",service="my_group/webapp"}
```

**Comment by klingerf** [comment]
Fixed by #19.
